name: badminton_score
description: A badminton score keeper application with customizable colors and sound effects.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  audioplayers: ^6.8.1
  flutter:
    sdk: flutter
  lucide_flutter: ^1.47.0
  segment_display: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
